<?php
namespace OW\Rules\Parser;

use Mockery as m;
use OW\Rules\Rule\BasicRule;
use OW\Rules\Filter\Post\StripTagsPostFilter;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-26 at 17:16:49.
 */
class StringFilterParserTest extends \PHPUnit_Framework_TestCase
{

    /**
     *
     * @var StringFilterParser
     */
    protected $object;
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new StringFilterParser();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        m::close();
    }

    /**
     * @covers OW\Rules\Parser\StringFilterParser::serialize
     * 
     */
    public function testSerialize()
    {
        $filter = new StripTagsPostFilter('<a><script>');
        $result = $this->object->serialize($filter);
        $this->assertEquals('strip_tags(<a><script>)', $result);
    }

    /**
     * @covers OW\Rules\Parser\StringFilterParser::parse
     * 
     */
    public function testParse()
    {
        $filter = $this->object->parse('html');
        $this->assertInstanceOf('\OW\Rules\Filter\Post\HtmlPostFilter', $filter);
        
        $filter = $this->object->parse('text');
        $this->assertInstanceOf('\OW\Rules\Filter\Post\TextPostFilter', $filter);
        $this->assertEquals([], $filter->getParams());
        
        $filter = $this->object->parse('strip_tags(<a><p><script>)');
        $this->assertInstanceOf('\OW\Rules\Filter\Post\StripTagsPostFilter', $filter);
        $this->assertEquals(['<a><p><script>'], $filter->getParams());

        $filter = $this->object->parse('attr(href)');
        $this->assertInstanceOf('\OW\Rules\Filter\Post\AttributePostFilter', $filter);
        $this->assertEquals(['href'], $filter->getParams());
    }
    
}
