<?php

namespace OW\Rules\Processor;

use Mockery as m;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-26 at 17:51:05.
 */
class CssRuleProcessorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var CssRuleProcessor
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $crawler = m::mock('Crawler');
        $this->object = new CssRuleProcessor($crawler);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        m::close();
    }

    /**
     * @covers OW\Rules\Processor\CssRuleProcessor::doEvalute
     * @todo   Implement testDoEvalute().
     */
    public function testDoEvalute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
    
    /**
     * @covers OW\Rules\Processor\BaseRuleProcessor::getCrawler
     * @todo   Implement testGetCrawler().
     */
    public function testGetCrawler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
    
    /**
     * @covers OW\Rules\Processor\BaseRuleProcessor::evaluate
     * @todo   Implement testEvaluate().
     */
    public function testEvaluate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
